---
title: "Final Project - Step 1"
author: "Melissa Young"
date: "July 31, 2022"
output: pdf_document
---

# Introdcution 
I currently work for a holding company with many subsidiaries.  My functions include finance manager, data warehousing and management as well as risk analysis and claims reserve projections on ultimate loss ratios.  Claims are the leading expense on an insuring business's profit statement outside of salaries and related.  Much emphasis is placed on predicting how a product will perform. This leads to evaluating the reasonableness of the warranty cost and claims experience to present loss reserves.  The subsidiary I will focus on for this project is a warranty group that specializes in servicing extended warranties on appliances (refrigerators, washers, dryers, stoves), TV's and other electronics (audio equipment, home wine coolers, portable air conditioners).  These products can have different warranty periods from 12 months to 5 years. The reason I am choosing this subsidiary is due to the fact that their operating income has fallen in the past couple of years.  Assumption is that this is due to an increase in claims experience since bringing on a large client.

# Research Questions
1. Can a predictive model help project claims assumptions using historical data and trends? 
2. Has there been in an increase in claims volume, or a decrease? 
3. Are there regional concentrations of dealers that are performing under contract terms? 
4. Can we pinpoint ill performing dealers with the model? 
5. Are the claims increasing or decreasing in a certain product group? 
6. Are the claims increasing or decreasing in relation to a certain product and manufacturer? 
7. Is there sufficient reserves for future claims? 
8. Are the warranty products priced correctly?

# Approach
Within the warranty business, the process of claims is approaching real time acceptance and denial. The certificate to replace a product, service a product and pay any associated costs with the claim needs to happen within a set time frame according to contract terms. Usually within 72 hours. An example within this project case with appliances would be to determine if the product is serviceable, start the process to get a tech out to the house.  If determined to be a total loss, send certificate for full replacement and any associated costs with that replacement such as food loss. I will begin with EDA on my data sets, determining if I have sufficient volume with 5 years of sales and claims historical.  I will then calculate the ultimate loss ratio to determine if the premiums outweigh the loss projections. With this information I can then conduct a correlation exercise to determine what data point has the most impact on the ultimate loss ratio. These steps will lead to the regression analysis on how the products will perform in the future and whether the business model is sustainable.   

# How your approach addresses (fully or partially) the problem. 
The earnings pattern of the warranties sold should more than cover the cost to service the product over the life of the warranty. My approach will address many aspects of what determines to be a good profit margin (15% or greater).  I can not say it will be fully addressed as there may be factors outside of my approach that I can address in future project work. When complete, a recommendation can be given as to the areas that need to be addressed to improve the products performance within the pricing model, claims costs and cost sharing.

# Data 

**Data Set 1:** Sales\  

**Source:** Internal system of record for warranty group\ 

This data set contains all sales information for the last 5 years.  Including contract number, product sold, manufacturer, dealer name, warranty terms, sale date, warranty costs and retail costs. 

**Data Set 2:** Claim\  

**Source:** Internal system of record for warranty group\ 

This data set contains all claims information for the last 5 years. Including contract number, loss date, payment date, total claim amount, parts amount, labor amount, servicing company. 
 
**Data Set 3:** Dealers\  

**Source:** Internal system of record for warranty group\ 

This data set contains all dealer information for the largest buying group within the warranty companies book of busies.  Including dealer location and demographics. 

# Required Packages 
library(plyr)\
library(dplyr)\
library(lmtest)\
library(readxl)\
library(tidyverse)\
library(car)\
library(lubridate)\
library(outliers)\
library(ggplot2)\
library(ggmap)\
library(data.table)

# Plots and Table Needs
The plots and tables to be used will be:\
1. Line graph\
2. Bar chart\
3. Histogram\
4. Scatter plot\
5. Boxplot\
6. Density Map\

# Questions for future steps
1. Do I have the correct data sets for the model? 
2. Will there be a need for extensive data transformations? 
3. Am I using the correct packages to accomplish my research questions? 
4. Will the outcome help improve product performance? 
5. Could there be other factors impacting the outcome of a product, such as an increase in salaries because our processes are outdated? 




